# Generated by Django 3.1.6 on 2021-02-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
